- name: "Install Node.js 13"
  become: true
  apt:
    name: ["npm", "nodejs"]
    state: latest
    update_cache: yes

- name: "Install PM2 Globally"
  npm:
    name: pm2
    global: yes

- name: "move env var to /etc/profile.d"
  become: true
  copy:
    src: myenv.sh
    dest: /etc/profile.d/
